glu.defView('todo.main', {
    layout:'hbox',

    items:[
        {
            flex:1,
            border:false
        },
        {
            title:'~~todo~~',
            width:400,
            layout:{
                type:'vbox',
                align:'stretch'
            },
            items:[
                {  //header
                    layout:'hbox',
                    height:25,
                    items:[
                        {
                            xtype:'checkbox',
                            value:'@>{allVisibleItemsAreCompleted}',
                            disabled:'@{!completeAllIsDisabled}',
                            width:20,
                            //handler : '@{batchComplete}'
                            listeners:{
                                change:'@{batchComplete}'
                            }
                        },
                        {
                            xtype:'textfield',
                            value:'@{newItemText}',
                            cls:'todo-newItemText',
                            emptyText:'~~newItemText~~',
                            enterKeyHandler:'@{addNewItem}',
                            width:300
                        }
                    ]
                },
                { //list body
                    layout:'vbox',
                    items:'@{todoList}',
                    bbar:[
                        {
                            xtype:'displayfield',
                            value:'@{itemsLeftText}'
                        },
                        {
                            xtype:'tbspacer'
                        },
                        {
                            xtype:'buttongroup',
                            flex:1,
                            activeItem:'@{filterMode}',
                            items:[
                                {
                                    text:'~~all~~',
                                    value:'all'
                                },
                                {
                                    text:'~~active~~',
                                    value:'active'
                                },
                                {
                                    text:'~~completed~~',
                                    value:'completed'
                                }
                            ]
                        },
                        {
                            xtype:'tbfill'
                        },
                        {
                            text:'@{clearCompletedText}',
                            handler:'@{clearCompleted}',
                            hidden:'@{!clearCompletedIsVisible}'
                        }
                    ]}

            ] }
        ,
        {
            flex:1,
            border:false
        }
    ]
});