// Generated by CoffeeScript 1.3.3
(function() {

  Given('the todo application', function() {
    var main, newItem, ns;
    ns = todo;
    main = null;
    newItem = null;
    Meaning(function() {
      var backend, res;
      res = todo.createMockBackend();
      backend = res.backend;
      main = glu.model({
        ns: 'todo',
        mtype: 'main'
      });
      return main.init();
    });
    ShouldHave('todo list is empty', function() {
      return expect(main.todoList.length).toBe(0);
    });
    return When('User clicks add button', function() {
      Meaning(function() {
        main.set('newItemText', '    Finish Todo spec     ');
        main.addNewItem();
        return newItem = main.todoList.getAt(0);
      });
      ShouldHave('change new item text to empty', function() {
        return expect(newItem.text).toBe('Finish Todo spec');
      });
      ShouldHave('change new item text ');
      return ShouldHave('add new todo ', function() {
        return expect(newItem.text).toBe('Finish Todo spec');
      });
    });
  });

}).call(this);
