// Generated by CoffeeScript 1.3.3
(function() {

  Given('the todo application', function() {
    var ns;
    ns = todo;
    Meaning(function() {
      var backend, main, res;
      res = todo.createMockBackend();
      backend = res.backend;
      main = glu.model({
        ns: 'todo',
        mtype: 'main'
      });
      return main.init();
    });
    ShouldHave('set value to true', function() {
      return expect(true).toBe(true);
    });
    return When('user enters in a new todo', function() {
      return Meaning(function() {
        return ShouldHave('trimmed the input', function() {
          return expect(true).toBe(false);
        });
      });
    });
  });

}).call(this);
